#Target_name:Dependencies
#<TAB>Commands
SRC=calender.c leap.c
INC =head.h
target: $(SRC) $(INC)
	gcc $(SRC) -o a.exe

run:target
	./a.exe	
# Build and run the unit tests
test: $(BUILD)
	gcc $(TEST_SRC) $(INC) -o $(TEST_OUTPUT) 
	./$(TEST_OUTPUT)

analyze: test memcheck staticcheck coverage sanitize_check

staticcheck:
	cppcheck --enable=all -iunity .

memcheck:
	valgrind ./$(TEST_OUTPUT)

sanitize_check:
	gcc -fsanitize=address -fno-omit-frame-pointer $(TEST_SRC) $(INC) -o $(TEST_OUTPUT) 
	./$(TEST_OUTPUT)

coverageCheck: $(TEST_SRC)
	gcc -fprofile-arcs -ftest-coverage $(TEST_SRC) $(INC) -o $(TEST_OUTPUT) 
	./$(TEST_OUTPUT)
	gcov -a Board_outline.c	

clean:
	rm a.exe
